# Generated by Django 4.2.6 on 2023-11-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
